### ISSUE TITLE
Pep should die if contextbroker is not running

### ISSUE THREAD

**Issue by mcarracedo** [telefonicaid/fiware-pep-steelskin#223] opened 2015-05-27 14:55 UTC
In the event of one contextbroker is not running, the corresponding PEP should die. This way the nginx will forward the requests to other active PEP-CB pair.

**Comment by fgalan** [comment] 2015-05-27 15:11
Is this bug needed to be fixed for IoTP v2.0?

**Comment by dmoranj** [comment] 2015-05-28 13:36
This is not a bug, as it was the expected functionality in the first place. As an improvement, we are creating a flag that lets the user configure whether he wants the PEP Proxy to stop on redirect error or return a 501 Code.

**Comment by dmoranj** [comment] 2015-06-03 09:25
Fixed in #225

**Closed by dmoranj** 2015-06-03 09:25 UTC
Labels: backlog, P7
